name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install mingw-w64
        run: sudo apt-get update && sudo apt-get install -y mingw-w64 libsensors-dev gcc pkg-config libwayland-dev libx11-dev libx11-xcb-dev libxkbcommon-x11-dev libgles2-mesa-dev libegl1-mesa-dev libffi-dev libxcursor-dev libvulkan-dev
      - uses: actions/setup-go@v5
        with:
            go-version: 1.21
      - name: Run Checks
        run: ./ci-checks.sh
