name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install mingw-w64
        run: sudo apt-get update && sudo apt-get install -y mingw-w64
      - uses: actions/setup-go@v5
        with:
            go-version: 1.21
      - name: Build Linux
        run: go build ./...
      - name: Build Windows
        env:
            CGO_ENABLED: 1
            CC:          x86_64-w64-mingw32-gcc
            CXX:         x86_64-w64-mingw32-g++
            GOOS:        windows
        run: go build ./...
